# Generated by Django 5.2 on 2025-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('code_barre', models.BigIntegerField(primary_key=True, serialize=False)),
                ('qte_suspendus', models.IntegerField()),
                ('qte_disponible', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='beneficiaire',
            fields=[
                ('id_beneficiaire', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='centre_social',
            fields=[
                ('id_centre_social', models.BigIntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id_client', models.BigIntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='magasin',
            fields=[
                ('id_magasin', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='panier',
            fields=[
                ('id_panier', models.BigIntegerField(primary_key=True, serialize=False)),
                ('retire', models.BooleanField(default=False)),
                ('complet', models.BooleanField(default=False)),
            ],
        ),
    ]
